apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-sender
  labels: 
    app: websocket-sender
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: websocket-sender
  template: 
    metadata:
      labels: 
        app: websocket-sender
    spec: 
      containers:
      - name: websocket-sender
        image: rlevine1440/websocket-sender
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 180
          periodSeconds: 10